// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: lobby.proto

package transfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LbcrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webid         string                 `protobuf:"bytes,1,opt,name=webid,proto3" json:"webid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LbcrRequest) Reset() {
	*x = LbcrRequest{}
	mi := &file_lobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LbcrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LbcrRequest) ProtoMessage() {}

func (x *LbcrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LbcrRequest.ProtoReflect.Descriptor instead.
func (*LbcrRequest) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *LbcrRequest) GetWebid() string {
	if x != nil {
		return x.Webid
	}
	return ""
}

type LbcrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobbyid       int32                  `protobuf:"varint,1,opt,name=lobbyid,proto3" json:"lobbyid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LbcrResponse) Reset() {
	*x = LbcrResponse{}
	mi := &file_lobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LbcrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LbcrResponse) ProtoMessage() {}

func (x *LbcrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LbcrResponse.ProtoReflect.Descriptor instead.
func (*LbcrResponse) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *LbcrResponse) GetLobbyid() int32 {
	if x != nil {
		return x.Lobbyid
	}
	return 0
}

type LbjnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webid         string                 `protobuf:"bytes,1,opt,name=webid,proto3" json:"webid,omitempty"`
	Lobbyid       int32                  `protobuf:"varint,2,opt,name=lobbyid,proto3" json:"lobbyid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LbjnRequest) Reset() {
	*x = LbjnRequest{}
	mi := &file_lobby_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LbjnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LbjnRequest) ProtoMessage() {}

func (x *LbjnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LbjnRequest.ProtoReflect.Descriptor instead.
func (*LbjnRequest) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *LbjnRequest) GetWebid() string {
	if x != nil {
		return x.Webid
	}
	return ""
}

func (x *LbjnRequest) GetLobbyid() int32 {
	if x != nil {
		return x.Lobbyid
	}
	return 0
}

var File_lobby_proto protoreflect.FileDescriptor

var file_lobby_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x22, 0x23, 0x0a, 0x0b, 0x6c, 0x62, 0x63, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x65, 0x62, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x65, 0x62, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x0c,
	0x6c, 0x62, 0x63, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c,
	0x6f, 0x62, 0x62, 0x79, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x0b, 0x6c, 0x62, 0x6a, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x65, 0x62, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x65, 0x62, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6c,
	0x6f, 0x62, 0x62, 0x79, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x6f,
	0x62, 0x62, 0x79, 0x69, 0x64, 0x42, 0x0e, 0x5a, 0x0c, 0x64, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_lobby_proto_rawDescOnce sync.Once
	file_lobby_proto_rawDescData []byte
)

func file_lobby_proto_rawDescGZIP() []byte {
	file_lobby_proto_rawDescOnce.Do(func() {
		file_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lobby_proto_rawDesc), len(file_lobby_proto_rawDesc)))
	})
	return file_lobby_proto_rawDescData
}

var file_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lobby_proto_goTypes = []any{
	(*LbcrRequest)(nil),  // 0: transfer.lbcrRequest
	(*LbcrResponse)(nil), // 1: transfer.lbcrResponse
	(*LbjnRequest)(nil),  // 2: transfer.lbjnRequest
}
var file_lobby_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lobby_proto_init() }
func file_lobby_proto_init() {
	if File_lobby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lobby_proto_rawDesc), len(file_lobby_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lobby_proto_goTypes,
		DependencyIndexes: file_lobby_proto_depIdxs,
		MessageInfos:      file_lobby_proto_msgTypes,
	}.Build()
	File_lobby_proto = out.File
	file_lobby_proto_goTypes = nil
	file_lobby_proto_depIdxs = nil
}
